check existence of youtube-dlp

diff --git a/etc/skel/.bin/piratesong b/etc/skel/.bin/piratesong
--- a/etc/skel/.bin/piratesong
+++ b/etc/skel/.bin/piratesong
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 set -e
+
+if ! command -v yt-dlp &> /dev/null
+then
+    echo "yt-dlp could not be found, please run sudo aura -Aca youtube-dlp-bin"
+    exit
+fi
+
 if [[ $1 == "-h" || $1 == "--help" ]]; then
+
     echo "Description: A shortcut to download youtube videos and converts to either mp3 ot mp4."
 
     printf "\n"
@@ -11,9 +19,9 @@ if [[ $1 == "-h" || $1 == "--help" ]]; then
     echo "  -s, --search    Searches for the video you're looking for."
 
 elif [[ $1 == "--mp3" ]]; then
-    youtube-dl -x --audio-format mp3 --prefer-ffmpeg $2
+    yt-dlp -x --audio-format mp3 --prefer-ffmpeg $2
 elif [[ "$1" == "--mp4" ]]; then
-    youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio" --merge-output-format mp4 $2
+    yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio" --merge-output-format mp4 $2
 elif [[ "$1" == "-s" || "$1" == "--search" ]]; then
-    youtube-dl "ytsearch1: $2"
+    yt-dlp "ytsearch1: $2"
 fi
